[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
miette = { version = "7.2.*", features = ["fancy"] }

[dev-dependencies]
pretty_assertions = "1.4.*"
