[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
day_one = { path = "../day_one" }
clap = { version = "4.5.*", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }

